# include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/app.router.dart"
    - "**/app.locator.dart"
    - "**/app.logger.dart"
    - "**/test_setup.mocks.dart"
  errors:
    todo: ignore
    invalid_annotation_target: ignore
    avoid_web_libraries_in_flutter: ignore
    use_build_context_synchronously: ignore
    avoid_renaming_method_parameters: ignore
