name: pinang_maksima_web
description: Pinang Maksima - Credit Scoring Web Apps

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  # Stacked Architecture
  stacked: ^3.0.0
  stacked_services: ^0.9.5
  stacked_hooks: ^0.2.2
  observable_ish: ^4.0.6
  # Data Models
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  # Utilities
  logger: ^1.1.0
  dartz: ^0.10.1
  dio: ^4.0.6
  intl: ^0.17.0
  url_launcher: ^6.1.5
  permission_handler: ^10.0.0
  downloads_path_provider_28: ^0.1.2
  flutter_local_notifications: ^12.0.3
  package_info_plus: ^1.4.3+1
  upgrader: ^4.6.1
  flutter_lorem: ^2.0.0
  slugify: ^2.0.0
  flutter_secure_storage: ^6.0.0
  # Network related
  connectivity: ^3.0.6
  provider: ^6.0.3
  http_certificate_pinning: ^2.0.4
  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # UI Related
  flutter_screenutil: ^5.5.4
  modal_progress_hud_nsn: ^0.3.0
  camera: ^0.10.0+1
  flutter_exif_rotation: ^0.5.1
  image_picker: ^0.8.5+3
  image_cropper: ^3.0.0
  cached_network_image: ^3.2.2
  flutter_spinkit: ^5.1.0
  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master
  mask_text_input_formatter: ^2.4.0
  advance_pdf_viewer: ^2.0.1
  flutter_pdfview: ^1.2.3
  dotted_line: ^3.1.0
  flutter_typeahead: ^4.1.0
  dotted_border: ^2.0.0+2
  glass: ^1.0.1+1
  auto_size_text: ^3.0.0
  flutter_svg: ^1.1.4
  flutter_exif_plugin: ^1.1.0
  exif: ^3.1.2
  native_exif: ^0.4.0
  flutter_animation_progress_bar: ^2.2.1
  carousel_slider: ^4.1.1
  file_picker: ^5.1.0
  syncfusion_flutter_pdfviewer: ^20.2.49-beta
  animations: ^2.0.4
  badges: ^2.0.3
  flutter_web_frame: ^0.0.3
  # Location Related
  location: ^4.4.0
  geolocator: ^8.2.1
  places_service: ^0.1.2
  place_picker: ^0.9.20-nullsafety
  google_maps_webservice: ^0.0.19
  # Firebase Related
  firebase_core: ^2.1.1
  firebase_analytics: ^10.0.4
  firebase_messaging: ^14.0.4
  geocode: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  # Flavor
  flutter_flavorizr: ^2.1.4
  # Code Generator
  build_runner: ^2.2.1
  stacked_generator: ^0.8.0
  hive_generator: ^2.0.0
  # Object Mocking
  mockito: ^5.3.1
  # Data Structure
  freezed: ^2.1.0+1
  json_serializable: ^6.3.2
  # Code Metrics
  dart_code_metrics: ^5.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito-BlackItalic.ttf
          weight: 900
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-ExtraBoldItalic.ttf
          weight: 800
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-SemiBoldItalic.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Italic.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-LightItalic.ttf
          weight: 300
        - asset: assets/fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito-ExtraLightItalic.ttf
          weight: 200
